### ISSUE TITLE
Billogram\Api\Item - $itemNo / item_no should be string

### ISSUE THREAD

**Issue by zombiefredrik** [FriendsOfApi/billogram#34]
Hello! Great work, guys! Trying to implement this fork right now. 
But I have the following issue:

According to the Billogram docs *item_no* is typed as string.
Since I fetch products marked with internal item codes (strings) I can't use items()->fetch()

    /**
     * @param int   $itemNo
     * @param array $param
     *
     * @return mixed|\Psr\Http\Message\ResponseInterface
     *
     * @see https://billogram.com/api/documentation#items_fetch
     */

And docs:

>item_no | string
>Identification for the item. Always present on existing items. If no item_no is given when creating >an item object, a new number is generated and assigned automatically. The item number is a >string and may contain other characters than just numerals. Must be unique. If the item_no is >changed on an item object, the new value must be used to refer to it from that point. If you want >automatic item-numbering, please do not set this parameter at all, not even to a null value. The >max length for item_no is 30 characters IF the value is non-numeric, otherwise (if the value is >numeric) the max value is 999999999.Example values: "207", "42-B081"

**Comment by Ibrahimhizeoui** [comment]
Hello!
You have right. It's fixed

**Comment by zombiefredrik** [comment]
Thanks. I'd change it myself and do a PR, but I thought it might have bigger implications and be a breaking change. Too bad there's no simple way of overloading methods in php.

**Comment by Nyholm** [comment]
Closed by #36
